DCT_METADATA = {
  "P2463-00": {
    "primary_code": True,
    "category": "DPF / Soot Load",
    "description": "Diesel Particulate Filter soot accumulation exceeds threshold",
    "system": "Aftertreatment System",
    "related_dtc_codes": [
      "P245E-11",
      "P2452-12",
      "P245E-1F",
      "P1194-00",
      "P2459-00",
      "P24A2-00",
      "P1629-00"
    ],
    "flow_type": "PRIMARY_ROOT"
  },

  "P245E-11": {
    "primary_code": False,
    "parent_code": "P2463-00",
    "category": "Sensor / Electrical",
    "description": "DPF differential pressure sensor low voltage",
    "system": "Aftertreatment System",
    "flow_type": "VALIDATION"
  },

  "P2452-12": {
    "primary_code": False,
    "parent_code": "P2463-00",
    "category": "Sensor / Overvoltage",
    "description": "DPF differential pressure sensor high voltage",
    "system": "Aftertreatment System",
    "flow_type": "VALIDATION"
  },

  "P245E-1F": {
    "primary_code": False,
    "parent_code": "P2463-00",
    "category": "Sensor / Pressure Deviation",
    "description": "DPF pressure sensor implausible signal",
    "system": "Aftertreatment System",
    "flow_type": "VALIDATION"
  },

  "P1194-00": {
    "primary_code": False,
    "parent_code": "P2463-00",
    "category": "Soot Load / Regeneration",
    "description": "Excessive soot load detected in DPF",
    "system": "Aftertreatment System",
    "flow_type": "VALIDATION"
  },

  "P2459-00": {
    "primary_code": False,
    "parent_code": "P2463-00",
    "category": "Regeneration Frequency",
    "description": "DPF regeneration occurring too frequently",
    "system": "Aftertreatment System",
    "flow_type": "PLACEHOLDER"
  },

  "P24A2-00": {
    "primary_code": False,
    "parent_code": "P2463-00",
    "category": "Regeneration Failure",
    "description": "DPF soot load not reducing after regeneration",
    "system": "Aftertreatment System",
    "flow_type": "PLACEHOLDER"
  },

  "P1629-00": {
    "primary_code": False,
    "parent_code": "P2463-00",
    "category": "Regeneration Inhibit",
    "description": "DPF regeneration inhibited due to system constraints",
    "system": "Aftertreatment System",
    "flow_type": "PLACEHOLDER"
  }
}
DCT_DATA =[
  {
    "step_id": 69,
    "dtc_code": "P2463-00",
    "step_order": 1,
    "question": "Is DTC P245E-11 active?",
    "yes_action": "Jump to P245E-11 diagnostic procedure.",
    "no_action": "Proceed to next primary DTC.",
    "created_at": "2026-04-30 06:34:01.377395+00",
    "details": "Check for P245E-11 / FC1881 using scan tool.",
    "expected_result": "Fault code status identified.",
    "next_step_if_yes": "P245E11_S1",
    "next_step_if_no": "P2463_S2",
    "step_code": "P2463_S1",
    "flow_type": "PRIMARY_CHECK"
  },
  {
    "step_id": 70,
    "dtc_code": "P2463-00",
    "step_order": 2,
    "question": "Is DTC P2452-12 active?",
    "yes_action": "Jump to P2452-12 diagnostic procedure.",
    "no_action": "Proceed to next primary DTC.",
    "created_at": "2026-04-30 06:34:01.377395+00",
    "details": "Check for P2452-12 / FC3133.",
    "expected_result": "Fault code status identified.",
    "next_step_if_yes": "P2452_S1",
    "next_step_if_no": "P2463_S3",
    "step_code": "P2463_S2",
    "flow_type": "PRIMARY_CHECK"
  },
  {
    "step_id": 71,
    "dtc_code": "P2463-00",
    "step_order": 3,
    "question": "Is DTC P245E-1F active?",
    "yes_action": "Jump to P245E-1F diagnostic procedure.",
    "no_action": "Proceed to next primary DTC.",
    "created_at": "2026-04-30 06:34:01.377395+00",
    "details": "Check for P245E-1F / FC1883.",
    "expected_result": "Fault code status identified.",
    "next_step_if_yes": "P245E1F_S1",
    "next_step_if_no": "P2463_S4",
    "step_code": "P2463_S3",
    "flow_type": "PRIMARY_CHECK"
  },
  {
    "step_id": 72,
    "dtc_code": "P2463-00",
    "step_order": 4,
    "question": "Is DTC P1194-00 active?",
    "yes_action": "Jump to P1194-00 diagnostic procedure.",
    "no_action": "Proceed to next primary DTC.",
    "created_at": "2026-04-30 06:34:01.377395+00",
    "details": "Check for P1194-00 / FC1981.",
    "expected_result": "Fault code status identified.",
    "next_step_if_yes": "P1194_S1",
    "next_step_if_no": "P2463_S5",
    "step_code": "P2463_S4",
    "flow_type": "PRIMARY_CHECK"
  },
  {
    "step_id": 73,
    "dtc_code": "P2463-00",
    "step_order": 5,
    "question": "Is DTC P2459-00 active?",
    "yes_action": "Jump to P2459-00 diagnostic procedure.",
    "no_action": "Proceed to next primary DTC.",
    "created_at": "2026-04-30 06:34:01.377395+00",
    "details": "Check for P2459-00 / FC3375.",
    "expected_result": "Fault code status identified.",
    "next_step_if_yes": "P2459_S1",
    "next_step_if_no": "P2463_S6",
    "step_code": "P2463_S5",
    "flow_type": "PRIMARY_CHECK"
  },
  {
    "step_id": 74,
    "dtc_code": "P2463-00",
    "step_order": 6,
    "question": "Is DTC P24A2-00 active?",
    "yes_action": "Jump to P24A2-00 diagnostic procedure.",
    "no_action": "Proceed to next primary DTC.",
    "created_at": "2026-04-30 06:34:01.377395+00",
    "details": "Check for P24A2-00 / FC3376.",
    "expected_result": "Fault code status identified.",
    "next_step_if_yes": "P24A2_S1",
    "next_step_if_no": "P2463_S7",
    "step_code": "P2463_S6",
    "flow_type": "PRIMARY_CHECK"
  },
  {
    "step_id": 75,
    "dtc_code": "P2463-00",
    "step_order": 7,
    "question": "Is DTC P1629-00 active?",
    "yes_action": "Jump to P1629-00 diagnostic procedure.",
    "no_action": "Proceed to final P2463 diagnosis.",
    "created_at": "2026-04-30 06:34:01.377395+00",
    "details": "Check for P1629-00 / FC2777.",
    "expected_result": "Fault code status identified.",
    "next_step_if_yes": "P1629_S1",
    "next_step_if_no": "P2463_S8",
    "step_code": "P2463_S7",
    "flow_type": "PRIMARY_CHECK"
  },
  {
    "step_id": 76,
    "dtc_code": "P2463-00",
    "step_order": 8,
    "question": "Proceed with P2463 soot load validation",
    "yes_action": "Perform regeneration or inspect DPF.",
    "no_action": "System normal.",
    "created_at": "2026-04-30 06:34:01.377395+00",
    "details": "All primary DTCs resolved. Evaluate actual DPF soot load.",
    "expected_result": "Soot load reflects actual condition.",
    "next_step_if_yes": "END",
    "next_step_if_no": "END",
    "step_code": "P2463_S8",
    "flow_type": "FINAL"
  },
  {
    "step_id": 77,
    "dtc_code": "P245E-11",
    "step_order": 1,
    "question": "Is DTC P245E-11 active?",
    "yes_action": "Proceed to freeze frame analysis",
    "no_action": "Return to parent flow.",
    "created_at": "2026-04-30 06:43:34.008104+00",
    "details": "1. Turn ignition OFF\n2. Locate OBD-II port\n3. Connect diagnostic scan tool\n4. Turn ignition ON (engine OFF)\n5. Power ON scan tool\n6. Open diagnostic app and connect to vehicle\n7. Start diagnosis and read fault codes",
    "expected_result": "Scan tool displays P245E-11 / FC1881 status.",
    "next_step_if_yes": "P245E11_S2",
    "next_step_if_no": "RETURN",
    "step_code": "P245E11_S1",
    "flow_type": "VALIDATION"
  },
  {
    "step_id": 78,
    "dtc_code": "P245E-11",
    "step_order": 2,
    "question": "Does freeze frame data confirm sensor voltage below 0.249 V?",
    "yes_action": "Proceed to visual inspection.",
    "no_action": "Check intermittent issue or revalidate.",
    "created_at": "2026-04-30 06:52:28.769546+00",
    "details": "Open diagnostic scan tool and ensure vehicle connection is active\r\nNavigate to Fault Codes / DTC menu\r\nSelect P245E-11 / FC1881\r\nOpen Freeze Frame Data / Snapshot Data\r\nRecord DPF differential pressure sensor voltage\r\nRecord Engine RPM\r\nRecord Coolant temperature\r\nRecord Vehicle speed\r\nRecord DPF upstream temperature\r\nRecord DPF downstream temperature\r\nSave or capture the freeze frame data (photo or export)",
    "expected_result": "Voltage below 0.249 V confirms fault condition.",
    "next_step_if_yes": "P245E11_S3",
    "next_step_if_no": "RETURN",
    "step_code": "P245E11_S2",
    "flow_type": "VALIDATION"
  },
  {
    "step_id": 79,
    "dtc_code": "P245E-11",
    "step_order": 3,
    "question": "Is any visible damage present in hoses, sensor, or wiring?",
    "yes_action": "Repair damaged wiring, replace connector, or reseat hoses and retest.",
    "no_action": "Proceed to sensor electrical checks.",
    "created_at": "2026-04-30 06:55:30.830077+00",
    "details": "1. Turn ignition OFF and wait 2 minutes for system de-energization.\r\n2. Locate the DPF assembly in the exhaust system under the vehicle.\r\n3. Identify the DPF differential pressure sensor and connected hoses.\r\n\r\nInspect Pressure Hoses:\r\n4. Check hoses for cracks, splits, or collapsed sections.\r\n5. Ensure hoses are firmly connected with no looseness or blowout.\r\n6. Check for soot or moisture deposits inside hose ends.\r\n\r\nInspect Sensor Connector:\r\n7. Check connector pins for bending, corrosion, or push-back.\r\n8. Inspect for water ingress or dirt inside connector housing.\r\n9. Ensure connector locking tab is fully engaged.\r\n\r\nInspect Sensor Body:\r\n10. Check for physical damage, cracks, or impact marks.\r\n11. Ensure sensor is securely mounted.\r\n\r\nInspect Wiring Harness:\r\n12. Check wiring for chafing against sharp edges, heat shields, or moving parts.\r\n13. Look for pinched, crushed, or damaged sections.",
    "expected_result": "No visible damage, disconnections, hose leaks, or wiring faults found.",
    "next_step_if_yes": "RETURN",
    "next_step_if_no": "P245E11_S4",
    "step_code": "P245E11_S3",
    "flow_type": "INSPECTION"
  },
  {
    "step_id": 81,
    "dtc_code": "P245E-11",
    "step_order": 4,
    "question": "Is sensor supply voltage within 4.75–5.25 V at Pin C?",
    "yes_action": "Proceed to ground circuit check.",
    "no_action": "Diagnose ECU 5V reference supply circuit (check fuses, wiring continuity, ECU connector pins).",
    "created_at": "2026-04-30 07:06:15.895083+00",
    "details": "WARNING: Ensure the DPF and exhaust area is cool before working (risk of burns).\r\n1. Set Digital Multimeter (DMM) to DC Voltage mode.\r\n2. Turn ignition ON (engine OFF).\r\n3. Locate the DPF differential pressure sensor connector.\r\n4. Do NOT disconnect the connector; use back-probing or a breakout harness.\r\n5. Identify pins (refer to wiring diagram):\r\n   - Pin A: Signal (0.249–4.75 V nominal)\r\n   - Pin B: Ground\r\n   - Pin C: 5V reference from ECU\r\n6. Probe Pin C (5V reference) against a known chassis ground.\r\n7. Record the voltage reading.",
    "expected_result": "Voltage reads between 4.75 V and 5.25 V (5V ±5%).",
    "next_step_if_yes": "P245E11_S5",
    "next_step_if_no": "RETURN",
    "step_code": "P245E11_S4",
    "flow_type": "ELECTRICAL"
  },
  {
    "step_id": 82,
    "dtc_code": "P245E-11",
    "step_order": 5,
    "question": "Is sensor ground voltage within 0–0.1 V at Pin B?",
    "yes_action": "Proceed to signal wire continuity check.",
    "no_action": "Inspect and repair ground path from sensor to ECU and chassis ground (clean connections, fix high resistance).",
    "created_at": "2026-04-30 07:09:11.647908+00",
    "details": "1. Ensure ignition is ON (engine OFF).\r\n2. Set Digital Multimeter (DMM) to DC Voltage mode.\r\n3. Locate the DPF differential pressure sensor connector.\r\n4. Use back-probing or breakout harness (do NOT disconnect connector).\r\n5. Identify Pin B (sensor ground).\r\n6. Probe Pin B against battery negative terminal.\r\n7. Record the voltage reading.",
    "expected_result": "Voltage reads between 0 V and 0.1 V (near zero).",
    "next_step_if_yes": "P245E11_S6",
    "next_step_if_no": "RETURN",
    "step_code": "P245E11_S5",
    "flow_type": "ELECTRICAL"
  },
  {
    "step_id": 83,
    "dtc_code": "P245E-11",
    "step_order": 6,
    "question": "Is signal wire continuity less than 2 ohms between sensor and ECU?",
    "yes_action": "Proceed to check for short to ground.",
    "no_action": "Repair or replace signal wire between sensor and ECU. Clear DTCs and retest.",
    "created_at": "2026-04-30 07:12:24.066641+00",
    "details": "1. Turn ignition OFF.\r\n2. Disconnect the DPF differential pressure sensor electrical connector.\r\n3. Disconnect the ECU connector (refer to workshop manual for correct pin identification).\r\n4. Set Digital Multimeter (DMM) to Resistance (Ω) mode.\r\n5. Identify the signal pin at the sensor connector.\r\n6. Identify the corresponding signal pin at the ECU connector.\r\n7. Probe between these two pins.\r\n8. Record the resistance value.",
    "expected_result": "Resistance is less than 2 Ω.",
    "next_step_if_yes": "P245E11_S7",
    "next_step_if_no": "RETURN",
    "step_code": "P245E11_S6",
    "flow_type": "ELECTRICAL"
  },
  {
    "step_id": 84,
    "dtc_code": "P245E-11",
    "step_order": 7,
    "question": "Is there NO short to ground on the signal wire (infinite resistance)?",
    "yes_action": "Proceed to sensor replacement check.",
    "no_action": "Locate and repair short to ground in signal wire (inspect insulation damage, contact with chassis or exhaust). Clear DTCs and retest.",
    "created_at": "2026-04-30 07:14:07.364531+00",
    "details": "1. Ensure ignition is OFF.\r\n2. Keep both sensor connector and ECU connector disconnected (from previous step).\r\n3. Set Digital Multimeter (DMM) to Resistance (Ω) mode.\r\n4. Identify the signal pin at the sensor connector.\r\n5. Probe between the signal pin and a known good chassis ground.\r\n6. Record the resistance value.",
    "expected_result": "Resistance reads OL (infinite).",
    "next_step_if_yes": "P245E11_S8",
    "next_step_if_no": "RETURN",
    "step_code": "P245E11_S7",
    "flow_type": "ELECTRICAL"
  },
  {
    "step_id": 85,
    "dtc_code": "P245E-11",
    "step_order": 8,
    "question": "Does replacing the DPF differential pressure sensor restore correct signal voltage (0.249–4.75 V)?",
    "yes_action": "Proceed to final verification step.",
    "no_action": "Escalate to ECU diagnostics or recheck wiring and connections.",
    "created_at": "2026-04-30 07:15:24.935101+00",
    "details": "1. Ensure ignition is OFF and exhaust system is fully cooled.\r\n2. Label and disconnect both pressure hoses from the sensor.\r\n3. Disconnect the sensor electrical connector.\r\n4. Remove mounting fasteners and remove the sensor.\r\n5. Install a new OEM DPF differential pressure sensor (do not use aftermarket parts).\r\n6. Reconnect and firmly seat both pressure hoses.\r\n7. Reconnect electrical connector (ensure locking tab clicks).\r\n8. Turn ignition ON (engine OFF).\r\n9. Use scan tool to monitor live data for sensor voltage.\r\n10. Verify signal voltage is within 0.249 V – 4.75 V range.",
    "expected_result": "Sensor voltage is within specification and no active P245E-11 fault is present.",
    "next_step_if_yes": "P245E11_S9",
    "next_step_if_no": "RETURN",
    "step_code": "P245E11_S8",
    "flow_type": "CORRECTIVE"
  },
  {
    "step_id": 86,
    "dtc_code": "P245E-11",
    "step_order": 9,
    "question": "Does fault code P245E-11 remain cleared after test cycle?",
    "yes_action": "Return to main P2463 diagnostic flow and continue with next primary DTC (P2452-12).",
    "no_action": "Re-inspect wiring, sensor, and connections or escalate to ECU diagnostics.",
    "created_at": "2026-04-30 07:17:09.629746+00",
    "details": "1. Using scan tool, navigate to Clear / Erase Diagnostic Trouble Codes.\r\n2. Clear all stored DTCs.\r\n3. Run a test cycle (ignition cycle or short drive if required).\r\n4. Re-scan vehicle for fault codes.\r\n5. Check if P245E-11 / FC1881 is present again.",
    "expected_result": "P245E-11 does not return after clearing.",
    "next_step_if_yes": "P2463_S2",
    "next_step_if_no": "RETURN",
    "step_code": "P245E11_S9",
    "flow_type": "FINAL"
  },
  {
    "step_id": 87,
    "dtc_code": "P2452-12",
    "step_order": 1,
    "question": "Is DTC P2452-12 / FC3133 active?",
    "yes_action": "Proceed to live data analysis to confirm over-voltage condition.",
    "no_action": "Return to main P2463 diagnostic flow and continue with next primary DTC.",
    "created_at": "2026-04-30 07:21:06.105584+00",
    "details": "1. Turn ignition OFF.\r\n2. Locate the OBD-II diagnostic port.\r\n3. Connect the diagnostic scan tool to the OBD-II port.\r\n4. Turn ignition ON (engine OFF).\r\n5. Power ON the scan tool.\r\n6. Open diagnostic application and establish connection with vehicle.\r\n7. Navigate to DTC / Fault Codes menu.\r\n8. Read and identify if P2452-12 / FC3133 is present.",
    "expected_result": "Scan tool displays whether P2452-12 / FC3133 is active or inactive.",
    "next_step_if_yes": "P2452_S2",
    "next_step_if_no": "RETURN",
    "step_code": "P2452_S1",
    "flow_type": "VALIDATION"
  },
  {
    "step_id": 88,
    "dtc_code": "P2452-12",
    "step_order": 2,
    "question": "Does live sensor data show voltage above 4.75 V?",
    "yes_action": "Proceed to inspect pressure hoses for blockage or disconnection.",
    "no_action": "Fault condition not confirmed. Return to main diagnostic flow or revalidate.",
    "created_at": "2026-04-30 07:23:17.758803+00",
    "details": "1. Ensure diagnostic scan tool is connected and communication with vehicle is active.\r\n2. Turn ignition ON (engine OFF).\r\n3. Navigate to Live Data / Data Stream in the scan tool.\r\n4. Select DPF Differential Pressure Sensor Voltage parameter.\r\n5. Observe the voltage reading in real time.\r\n6. Record the sensor voltage value.",
    "expected_result": "Sensor voltage is greater than 4.75 V, confirming over-voltage condition.",
    "next_step_if_yes": "P2452_S3",
    "next_step_if_no": "RETURN",
    "step_code": "P2452_S2",
    "flow_type": "VALIDATION"
  },
  {
    "step_id": 89,
    "dtc_code": "P2452-12",
    "step_order": 3,
    "question": "Are DPF pressure hoses free from blockage, damage, and properly connected?",
    "yes_action": "Proceed to check for short to battery (B+) on signal wire.",
    "no_action": "Clear blockage or replace damaged hose. Clear DTCs and retest.",
    "created_at": "2026-04-30 07:24:29.674768+00",
    "details": "1. Turn ignition OFF and allow exhaust system and DPF to cool completely.\r\n2. Open the hood and locate the DPF differential pressure sensor (mounted near firewall or exhaust system).\r\n3. Identify both pressure hoses connected to the sensor:\r\n   - Upstream hose (before DPF / high-pressure side)\r\n   - Downstream hose (after DPF / low-pressure side)\r\n4. Inspect hoses for disconnection, cracks, or splits.\r\n5. Carefully disconnect both hoses from the sensor.\r\n6. Visually inspect inside each hose for soot blockage or deposits.\r\n7. Use a thin probe or low-pressure compressed air (max 2 bar) to check for free airflow.\r\n8. Reconnect both hoses securely to the sensor.",
    "expected_result": "Both hoses are clear, undamaged, and properly connected.",
    "next_step_if_yes": "P2452_S4",
    "next_step_if_no": "RETURN",
    "step_code": "P2452_S3",
    "flow_type": "INSPECTION"
  },
  {
    "step_id": 90,
    "dtc_code": "P2452-12",
    "step_order": 6,
    "question": "Does fault code P2452-12 remain cleared after test cycle?",
    "yes_action": "Return to main P2463 diagnostic flow and continue with next primary DTC.",
    "no_action": "Re-inspect system or escalate to ECU diagnostics if fault persists.",
    "created_at": "2026-04-30 07:29:54.814771+00",
    "details": "1. Using scan tool, clear all Diagnostic Trouble Codes (DTCs).\r\n2. Perform the required DPF diagnostic drive cycle.\r\n3. Re-scan the vehicle after the test cycle.\r\n4. Check if P2452-12 / FC3133 is present again.",
    "expected_result": "P2452-12 does not re-trigger after clearing and test cycle.",
    "next_step_if_yes": "P2463_S3",
    "next_step_if_no": "RETURN",
    "step_code": "P2452_S6",
    "flow_type": "FINAL"
  },
  {
    "step_id": 91,
    "dtc_code": "P245E-1F",
    "step_order": 1,
    "question": "Is DTC P245E-1F / FC1883 active?",
    "yes_action": "Proceed to pressure value validation (baseline check at key ON/OFF).",
    "no_action": "Return to main P2463 diagnostic flow and continue with next primary DTC.",
    "created_at": "2026-04-30 07:32:19.841535+00",
    "details": "1. Turn ignition OFF.\r\n2. Locate the OBD-II diagnostic port.\r\n3. Connect the diagnostic scan tool to the OBD-II port.\r\n4. Turn ignition ON (engine OFF).\r\n5. Power ON the scan tool.\r\n6. Open diagnostic application and establish connection with vehicle.\r\n7. Navigate to DTC / Fault Codes menu.\r\n8. Read and identify if P245E-1F / FC1883 is present.",
    "expected_result": "Scan tool displays whether P245E-1F / FC1883 is active or inactive.",
    "next_step_if_yes": "P245E1F_S2",
    "next_step_if_no": "RETURN",
    "step_code": "P245E1F_S1",
    "flow_type": "VALIDATION"
  },
  {
    "step_id": 92,
    "dtc_code": "P245E-1F",
    "step_order": 3,
    "question": "Is sensor wiring and connector free from damage or faults?",
    "yes_action": "Proceed to sensor evaluation/replacement.",
    "no_action": "Repair wiring/connectors and retest. Clear DTCs before re-evaluation.",
    "created_at": "2026-04-30 07:34:28.451384+00",
    "details": "1. Turn ignition OFF.\r\n2. Locate the DPF differential pressure sensor electrical connector.\r\n3. Inspect the connector for:\r\n   - Loose connection\r\n   - Corroded or bent terminals\r\n4. Inspect the wiring harness from sensor to ECU for:\r\n   - Damaged or cut insulation\r\n   - Broken wires\r\n   - Signs of heat damage or chafing\r\n5. Ensure all connections are secure and properly seated.",
    "expected_result": "Wiring and connectors are intact, clean, and securely connected.",
    "next_step_if_yes": "P245E1F_S4",
    "next_step_if_no": "RETURN",
    "step_code": "P245E1F_S3",
    "flow_type": "INSPECTION"
  },
  {
    "step_id": 93,
    "dtc_code": "P245E-1F",
    "step_order": 4,
    "question": "Does replacing the DPF differential pressure sensor restore normal pressure (< 1.5 kPa at key ON, engine OFF)?",
    "yes_action": "Clear DTCs and return to main P2463 diagnostic flow.",
    "no_action": "Escalate to ECU diagnostics or re-evaluate system if fault persists.",
    "created_at": "2026-04-30 07:35:07.070446+00",
    "details": "1. Ensure ignition is OFF and exhaust system is fully cooled.\r\n2. Confirm that pressure hoses and wiring are functioning correctly.\r\n3. Disconnect the electrical connector from the DPF differential pressure sensor.\r\n4. Disconnect both pressure hoses from the sensor.\r\n5. Remove the sensor from its mounting bracket.\r\n6. Install a new OEM DPF differential pressure sensor.\r\n7. Reconnect both pressure hoses securely.\r\n8. Reconnect the electrical connector (ensure proper locking).\r\n9. Turn ignition ON (engine OFF).\r\n10. Use scan tool to monitor DPF differential pressure value and verify it is below 1.5 kPa.",
    "expected_result": "DPF pressure reading is below 1.5 kPa at key ON (engine OFF), indicating correct baseline reference.",
    "next_step_if_yes": "P245E1F_S5",
    "next_step_if_no": "RETURN",
    "step_code": "P245E1F_S4",
    "flow_type": "CORRECTIVE"
  },
  {
    "step_id": 94,
    "dtc_code": "P245E-1F",
    "step_order": 5,
    "question": "Does fault code P245E-1F remain cleared after ignition cycle?",
    "yes_action": "Return to main P2463 diagnostic flow and continue with next primary DTC.",
    "no_action": "Re-inspect system or escalate to ECU diagnostics if fault persists.",
    "created_at": "2026-04-30 07:35:46.464954+00",
    "details": "1. Using scan tool, clear all Diagnostic Trouble Codes (DTCs).\r\n2. Turn ignition OFF.\r\n3. Turn ignition ON (engine OFF).\r\n4. Re-scan the vehicle for fault codes.\r\n5. Check if P245E-1F / FC1883 is present again.\r\n\r\nNote:\r\n- Some OEMs may require sensor zero-point calibration or offset reset.\r\n- DPF regeneration verification drive cycle may be needed.\r\n- Refer to manufacturer-specific scan tool procedures if applicable.",
    "expected_result": "P245E-1F does not reappear after clearing and ignition cycle.",
    "next_step_if_yes": "P2463_S4",
    "next_step_if_no": "RETURN",
    "step_code": "P245E1F_S5",
    "flow_type": "FINAL"
  },
  {
    "step_id": 95,
    "dtc_code": "P1194-00",
    "step_order": 1,
    "question": "Is DTC P1194 / FC1981 active?",
    "yes_action": "Proceed to soot load validation (DPF load condition).",
    "no_action": "Return to main P2463 diagnostic flow and continue with next primary DTC.",
    "created_at": "2026-04-30 07:36:54.267973+00",
    "details": "1. Turn ignition OFF.\r\n2. Locate the OBD-II diagnostic port.\r\n3. Connect the diagnostic scan tool to the OBD-II port.\r\n4. Turn ignition ON (engine OFF).\r\n5. Power ON the scan tool.\r\n6. Open diagnostic application and establish connection with vehicle.\r\n7. Navigate to DTC / Fault Codes menu.\r\n8. Read and identify if P1194 / FC1981 is present.",
    "expected_result": "Scan tool displays whether P1194 / FC1981 is active or inactive.",
    "next_step_if_yes": "P1194_S2",
    "next_step_if_no": "RETURN",
    "step_code": "P1194_S1",
    "flow_type": "VALIDATION"
  },
  {
    "step_id": 96,
    "dtc_code": "P1194-00",
    "step_order": 2,
    "question": "Are related DTCs (P2459, P24A2, P1629) also active?",
    "yes_action": "Proceed to next diagnostic step for soot load evaluation.",
    "no_action": "Proceed to next diagnostic step for soot load evaluation.",
    "created_at": "2026-04-30 07:38:03.031844+00",
    "details": "1. Using scan tool, navigate to DTC / Fault Codes menu.\r\n2. Check for presence of the following additional primary codes:\r\n   - P2459-00 / FC3375 (Frequent regeneration)\r\n   - P24A2-00 / FC3376 (Soot load not reduced after regen)\r\n   - P1629-00 / FC2777 (Regeneration inhibit active)\r\n3. Record whether any of these codes are active.",
    "expected_result": "One or more related soot-load primary DTCs may be present along with P1194.",
    "next_step_if_yes": "P1194_S3",
    "next_step_if_no": "P1194_S3",
    "step_code": "P1194_S2",
    "flow_type": "ROUTING"
  },
  {
    "step_id": 97,
    "dtc_code": "P1194-00",
    "step_order": 3,
    "question": "Is combined soot load greater than 8.5 g/L?",
    "yes_action": "Proceed to next step for regeneration or further evaluation.",
    "no_action": "Fault condition not confirmed. Return to main diagnostic flow or re-evaluate.",
    "created_at": "2026-04-30 07:39:50.365435+00",
    "details": "1. Ensure diagnostic scan tool is connected and communication is active.\r\n2. Turn ignition ON (engine may be OFF or running as required).\r\n3. Navigate to Live Data / Sensor Data in the diagnostic application.\r\n4. Locate parameter: \"Combined Soot Load Estimate\".\r\n5. Observe and record the soot load value (g/L).",
    "expected_result": "Combined soot load estimate is greater than 8.5 g/L, confirming high soot condition.",
    "next_step_if_yes": "P1194_S4",
    "next_step_if_no": "RETURN",
    "step_code": "P1194_S3",
    "flow_type": "VALIDATION"
  },
  {
    "step_id": 98,
    "dtc_code": "P1194-00",
    "step_order": 4,
    "question": "Is rail pressure within 414–420 bar and no related subsystem faults present?",
    "yes_action": "Proceed to next step for regeneration evaluation.",
    "no_action": "Resolve fuel system / temperature sensor / HC dosing issues before continuing. Clear DTCs and retest.",
    "created_at": "2026-04-30 07:40:25.435141+00",
    "details": "1. Ensure scan tool is connected and communication is active.\r\n2. Navigate to ECU Live Data.\r\n3. Go to Fuel System parameters.\r\n4. Locate and monitor Rail Pressure Sensor value.\r\n5. Verify rail pressure is within 414–420 bar.\r\n6. Check for any active DPF temperature sensor-related fault codes.\r\n7. Check for any HC metering unit-related fault codes.\r\n8. Record all observations.",
    "expected_result": "Rail pressure is within 414–420 bar and no related subsystem DTCs are active.",
    "next_step_if_yes": "P1194_S5",
    "next_step_if_no": "RETURN",
    "step_code": "P1194_S4",
    "flow_type": "VALIDATION"
  },
  {
    "step_id": 99,
    "dtc_code": "P1194-00",
    "step_order": 5,
    "question": "Are all pre-conditions met to perform DPF restriction test?\r\nPRE conditions: PRE-CONDITIONS:\r\n1. Test must be initiated within 1 hour of stationary regeneration.\r\n2. No active RPM limitation or sensor-related error codes.\r\n3. Engine not in regeneration mode.\r\n4. Coolant temperature > 60°C.\r\n5. Clutch not pressed.\r\n6. Brake not applied.\r\n7. Parking brake engaged.\r\n8. PTO OFF.\r\n9. Accelerator not pressed.\r\n10. Gear in NEUTRAL.\r\n11. Engine at IDLE.\r\n\r\nTEST EXECUTION:\r\n1. Navigate: Diagnostic Scan → Actuator Test → DPF Choking Test.\r\n2. Select \"Restriction Test\".\r\n3. Change STOP → START.\r\n4. Engine RPM increases to ~2000 RPM.\r\n5. Test runs for 3–4 minutes.\r\n6. System monitors delta pressure.\r\n7. Engine returns to idle after completion.\r\n\r\nRESULT INTERPRETATION:\r\n- PASS → DPF is OK → investigate other causes.\r\n- FAIL → DPF clogged → clean or replace at authorized center.\r\n\r\nNOTES:\r\n- Test aborts if brake/accelerator pressed.\r\n- Any deviation in preconditions aborts test.",
    "yes_action": "Proceed to perform DPF restriction test.",
    "no_action": "Resolve unmet pre-conditions before continuing.",
    "created_at": "2026-04-30 07:41:36.225204+00",
    "details": "Check if all required pre-conditions for DPF Restriction Test are satisfied. \r\nIf needed, follow sub-step P1194_S5_1 for detailed SOP and pre-condition checklist.",
    "expected_result": "All required pre-conditions are satisfied for initiating DPF restriction test.",
    "next_step_if_yes": "P1194_S5_2",
    "next_step_if_no": "RETURN",
    "step_code": "P1194_S5",
    "flow_type": "VALIDATION"
  },
  {
    "step_id": 100,
    "dtc_code": "P1194-00",
    "step_order": 501,
    "question": "View detailed SOP for DPF Restriction Test",
    "yes_action": None,
    "no_action": None,
    "created_at": "2026-04-30 07:41:47.604311+00",
    "details": "PRE-CONDITIONS:\r\n1. Test must be initiated within 1 hour of stationary regeneration.\r\n2. No active RPM limitation or sensor-related error codes.\r\n3. Engine not in regeneration mode.\r\n4. Coolant temperature > 60°C.\r\n5. Clutch not pressed.\r\n6. Brake not applied.\r\n7. Parking brake engaged.\r\n8. PTO OFF.\r\n9. Accelerator not pressed.\r\n10. Gear in NEUTRAL.\r\n11. Engine at IDLE.\r\n\r\nTEST EXECUTION:\r\n1. Navigate: Diagnostic Scan → Actuator Test → DPF Choking Test.\r\n2. Select \"Restriction Test\".\r\n3. Change STOP → START.\r\n4. Engine RPM increases to ~2000 RPM.\r\n5. Test runs for 3–4 minutes.\r\n6. System monitors delta pressure.\r\n7. Engine returns to idle after completion.\r\n\r\nRESULT INTERPRETATION:\r\n- PASS → DPF is OK → investigate other causes.\r\n- FAIL → DPF clogged → clean or replace at authorized center.\r\n\r\nNOTES:\r\n- Test aborts if brake/accelerator pressed.\r\n- Any deviation in preconditions aborts test.",
    "expected_result": None,
    "next_step_if_yes": None,
    "next_step_if_no": None,
    "step_code": "P1194_S5_1",
    "flow_type": "INFO"
  },
  {
    "step_id": 101,
    "dtc_code": "P1194-00",
    "step_order": 6,
    "question": "After DPF restriction test, are all related DTCs cleared?",
    "yes_action": "Return to main P2463 diagnostic flow and continue with next primary DTC.",
    "no_action": "Re-evaluate DPF condition, regeneration system, or escalate for further diagnostics.",
    "created_at": "2026-04-30 07:42:48.980685+00",
    "details": "1. Ensure DPF restriction test has been completed successfully (refer P1194_S5_2).\r\n2. Confirm all pre-conditions were satisfied during the test.\r\n3. Using scan tool, re-read all DTCs.\r\n4. Verify that the following DTCs are NOT present:\r\n   - P1194 / FC1981\r\n   - P2459-00 / FC3375\r\n   - P24A2-00 / FC3376\r\n   - P1629-00 / FC2777",
    "expected_result": "All related DTCs are cleared and do not reappear after the test cycle.",
    "next_step_if_yes": "P2463_S5",
    "next_step_if_no": "RETURN",
    "step_code": "P1194_S6",
    "flow_type": "FINAL"
  },
  {
    "step_id": 102,
    "dtc_code": "P2459-00",
    "step_order": 1,
    "question": "Diagnostic procedure for P2459-00 is not yet available. Continue?",
    "yes_action": "Return to P2463 diagnostic flow.",
    "no_action": "Return to P2463 diagnostic flow.",
    "created_at": "2026-04-30 07:44:21.679244+00",
    "details": "User has been routed here from P2463 flow. Detailed diagnostic steps for P2459-00 (Frequent Regeneration) are not yet implemented in the system.",
    "expected_result": "No diagnostic execution performed.",
    "next_step_if_yes": "P2463_S6",
    "next_step_if_no": "P2463_S6",
    "step_code": "P2459_S1",
    "flow_type": "PLACEHOLDER"
  },
  {
    "step_id": 103,
    "dtc_code": "P24A2-00",
    "step_order": 1,
    "question": "Diagnostic procedure for P24A2-00 is not yet available. Continue?",
    "yes_action": "Return to P2463 diagnostic flow.",
    "no_action": "Return to P2463 diagnostic flow.",
    "created_at": "2026-04-30 07:44:28.216899+00",
    "details": "User has been routed here from P2463 flow. Detailed diagnostic steps for P24A2-00 (Soot load not reduced after regeneration) are not yet implemented in the system.",
    "expected_result": "No diagnostic execution performed.",
    "next_step_if_yes": "P2463_S7",
    "next_step_if_no": "P2463_S7",
    "step_code": "P24A2_S1",
    "flow_type": "PLACEHOLDER"
  },
  {
    "step_id": 104,
    "dtc_code": "P1629-00",
    "step_order": 1,
    "question": "Diagnostic procedure for P1629-00 is not yet available. Continue?",
    "yes_action": "Return to P2463 diagnostic flow.",
    "no_action": "Return to P2463 diagnostic flow.",
    "created_at": "2026-04-30 07:44:34.906514+00",
    "details": "User has been routed here from P2463 flow. Detailed diagnostic steps for P1629-00 (Regen inhibit active) are not yet implemented in the system.",
    "expected_result": "No diagnostic execution performed.",
    "next_step_if_yes": "P2463_S8",
    "next_step_if_no": "P2463_S8",
    "step_code": "P1629_S1",
    "flow_type": "PLACEHOLDER"
  },
  {
    "step_id": 105,
    "dtc_code": "P245E-1F",
    "step_order": 2,
    "question": "After inspecting/clearing hoses, is pressure below 1.5 kPa at key ON (engine OFF)?",
    "yes_action": "Clear DTCs and verify fault does not return (final validation).",
    "no_action": "Proceed to further diagnostics (sensor/electrical checks).",
    "created_at": "2026-04-30 07:49:26.127608+00",
    "details": "1. Turn ignition OFF and allow exhaust system to cool.\r\n2. Open hood and locate the DPF differential pressure sensor.\r\n3. Identify both pressure hoses connected to the sensor ports.\r\n4. Inspect hoses for:\r\n   - Soot buildup or blockage\r\n   - Cracks or physical damage\r\n   - Loose or disconnected fittings\r\n   - Kinks restricting airflow\r\n5. If required, remove hoses and inspect internally for soot accumulation.\r\n6. Clear any blockage using low-pressure air or cleaning method.\r\n7. Reconnect hoses securely.\r\n8. Turn ignition ON (engine OFF).\r\n9. Check DPF differential pressure reading using scan tool.",
    "expected_result": "Pressure reading drops below 1.5 kPa at key ON (engine OFF).",
    "next_step_if_yes": "P245E1F_S3",
    "next_step_if_no": "P245E1F_S3",
    "step_code": "P245E1F_S2",
    "flow_type": "INSPECTION"
  },
  {
    "step_id": 106,
    "dtc_code": "P2452-12",
    "step_order": 4,
    "question": "Is signal wire free from short to battery (B+)?",
    "yes_action": "Proceed to sensor replacement step.",
    "no_action": "Trace and repair short to battery (B+) in signal wire (inspect for contact with live circuits or damaged insulation). Clear DTCs and retest.",
    "created_at": "2026-04-30 08:44:19.757237+00",
    "details": "1. Turn ignition OFF.\r\n2. Disconnect the DPF differential pressure sensor electrical connector.\r\n3. Disconnect the corresponding ECU connector pin for the sensor signal wire (refer to wiring diagram).\r\n4. Set Digital Multimeter (DMM) to DC Voltage mode.\r\n5. Turn ignition ON (engine OFF).\r\n6. At the sensor connector side, probe the signal wire against chassis ground.\r\n7. Record the voltage reading.",
    "expected_result": "Voltage reads 0 V with both sensor and ECU disconnected.",
    "next_step_if_yes": "P2452_S5",
    "next_step_if_no": "RETURN",
    "step_code": "P2452_S4",
    "flow_type": "ELECTRICAL"
  },
  {
    "step_id": 107,
    "dtc_code": "P2452-12",
    "step_order": 5,
    "question": "Does replacing the DPF differential pressure sensor restore correct voltage (0.249–4.75 V)?",
    "yes_action": "Proceed to final verification step.",
    "no_action": "Escalate to ECU diagnostics or recheck wiring and connections.",
    "created_at": "2026-04-30 08:44:32.15844+00",
    "details": "1. Ensure ignition is OFF and exhaust system is fully cooled.\r\n2. Confirm that supply voltage, ground, signal wire, and hose checks are within specification.\r\n3. Disconnect both pressure hoses from the DPF differential pressure sensor.\r\n4. Disconnect the sensor electrical connector.\r\n5. Remove mounting fasteners and remove the sensor.\r\n6. Install a new OEM DPF differential pressure sensor.\r\n7. Reconnect both pressure hoses and ensure no air leaks.\r\n8. Reconnect the electrical connector (ensure locking tab clicks).\r\n9. Turn ignition ON (engine OFF).\r\n10. Monitor live data using scan tool and verify sensor voltage is within 0.249 V – 4.75 V.",
    "expected_result": "Sensor voltage is within specification and P2452-12 / FC3133 is no longer active.",
    "next_step_if_yes": "P2452_S6",
    "next_step_if_no": "RETURN",
    "step_code": "P2452_S5",
    "flow_type": "CORRECTIVE"
  }
]